### ISSUE TITLE
phpcs fails on latest version

### ISSUE THREAD

**Issue by pixelplant** [lorisleiva/laravel-docker#20]
```
phpcs --standard=PSR2 --extensions=php --ignore=".(blade.php)" app
/bin/bash: line 78: phpcs: command not found
```

I saw that codesniffer is now installed using composer, but changing the line to
``` 
./vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=".(blade.php)" app
/bin/bash: line 78: ./vendor/bin/phpcs: No such file or directory
```
did not fix the issue.

Is there something I'm missing?

**Comment by pixelplant** [comment]
Seems the new path should be
```
~/.composer/vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=".(blade.php)" app
```

**Comment by lorisleiva** [comment]
Thanks for raising this! I've add to change the way PHPCS is installed and I didn't think about this consequence. Let me know if you can think of a way to set it up back to the way it was.

**Comment by fgilio** [comment]
Oh crap didn't think about this when making the change. @lorisleiva time you update your post? 😅

**Comment by AngeloAvv** [comment]
Here I am with the very same error!

```
phpcs --standard=PSR2 --extensions=php --ignore=app/Console/*,app/Support/helpers.php app
/bin/bash: line 66: phpcs: command not found
```

So what's the best way to set it back properly?

**Comment by fgilio** [comment]
Until this is properly fixed in the image, @pixelplant solution should work `~/.composer/vendor/bin/phpcs`. And it should continue working when the image is fixed

**Comment by lorisleiva** [comment]
@fgilio Amazing, thanks for sharing this piece of code. I'll update the dockerfiles to make the composer directory explicit.

I'm going to reopen this until it works.

**Comment by fgilio** [comment]
@AngeloAvv @pixelplant have you had a chance to test with the latest version? I don't have any project with the CI running the phpcs job

**Comment by pixelplant** [comment]
@fgilio Yes, it works now without specifying the complete path to phpcs, like before.

**Comment by fgilio** [comment]
Awesome! Thanks for the update

**Comment by lorisleiva** [comment]
Perfect. Thanks everyone for your help in this issue.

**Comment by HighCoData** [comment]
I'm still having issues after clearing all cache and rebuilding the composer package....
None of the applicaitons in vendor/bin are not accasible.

I'm using the latest image

**Comment by lorisleiva** [comment]
I've added back the `./vendor/bin` path in the `$PATH` variable.

Please let me know if it works once the new images have been built. 🤞

**Comment by bseresia** [comment]
No image fixed this as well..
Thanks!

**Comment by lorisleiva** [comment]
@HighCoData Is your issue fixed by the latest image?

**Comment by HighCoData** [comment]
yes it is, thanks

**Comment by AngeloAvv** [comment]
@lorisleiva seems like the issue is back again with the following image:

lorisleiva/laravel-docker:7.4
